a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [es, fr, en, el]      # [1-a]
    default_locale: es             # [1-b]
    required_locales: [fr]         # [1-c]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [2]