a2lix_translation_form:
    locale_provider: default
    locales: '%app.languages%'
    default_locale: '%app.default_language%'
    required_locales: [es]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"