doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'sqlsrv'
                # server_version: '5.7'
                charset: UTF-8
                default_table_options:
                    collate: utf8_unicode_ci
            customer:
                # configure these for your database server
                url: '%env(DATABASE_CUSTOMER_URL)%'
                driver: 'sqlsrv'
                # server_version: '5.7'
                charset: utf8mb4
                logging: false 
                default_table_options:
                    collate: utf8mb4_unicode_ci

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            customer:
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
#                    translatable:
#                        type: annotation
#                        alias: Gedmo
#                        prefix: Gedmo\Translatable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
#                    loggable:
#                        type: annotation
#                       alias: Gedmo
#                       prefix: Gedmo\Loggable\Entity
#                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                   tree:
#                       type: annotation
#                       alias: Gedmo
#                       prefix: Gedmo\Tree\Entity
#                       dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"



    #     url: '%env(resolve:DATABASE_URL)%'
    #     driver: 'pdo_sqlsrv'
    #     charset: utf8mb4
    #     default_table_options:
    #         collate: utf8mb4_unicode_ci
    # orm:
    #     auto_generate_proxy_classes: true
    #     naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #     auto_mapping: true
    #     mappings:
    #         App:
    #             is_bundle: false
    #             type: annotation
    #             dir: '%kernel.project_dir%/src/Entity'
    #             prefix: 'App\Entity'
    #             alias: App
