liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    driver:               "gd"
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeActio

    filter_sets:
        # HEADERS
        home_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        full_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        doble_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        # CALL TO ACTION
        call_to_action:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        # VECTORS
        picto_header:
            quality: 100
            filters:
                scale:
                    dim: [1920, 1080]

        picto_grid:
            quality: 100
            filters:
                scale:
                    dim: [1920, 1080]

        picto_cases:
            quality: 100
            filters:
                scale:
                    dim: [1920, 1080]

        # INSIGHTS
        insights_grid:
            quality: 75
            filters:
                scale:
                    dim: [1040, 585]

        # ARTICLES
        article_box:
            quality: 75
            filters:
                scale:
                    dim: [1040, 585]

        generic_foto:
            quality: 75
            filters:
                scale:
                    dim: [460, 360]

        # LAWYERS
        lawyers_header:
            quality: 75
            filters:
                scale:
                    dim: [1800, 1000]

        lawyers_grid:
            quality: 75
            filters:
                scale:
                    dim: [900, 500]

        lawyers_team:
            quality: 75
            filters:
                scale:
                    dim: [1800, 1000]


        # Mejor hacer un solo filtro global para todos los tipos de cabeceras, en caso necesario se dan de alta el resto
        # desks_header:
        #     quality: 75
        #     filters:
        #         scale:
        #             dim: [1280, 720]

        # practices_header:
        #     quality: 75
        #     filters:
        #         scale:
        #             dim: [1280, 720]

        # sectors_header:
        #     quality: 75
        #     filters:
        #         scale:
        #             dim: [1280, 720]

        # product_header:
        #     quality: 75
        #     filters:
        #         scale:
        #             dim: [1280, 720]

        # product_grid:
        #     quality: 75
        #     filters:
        #         scale:
        #             dim: [350, 200]
