liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    driver:               "gd"
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeActio

    filter_sets:

        desks_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        lawyers_grid:
            quality: 75
            filters:
                scale:
                    dim: [350, 200]

        lawyers_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        practices_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]

        sectors_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]
        prodruct_grid:
            quality: 75
            filters:
                scale:
                    dim: [350, 200]
        prodruct_header:
            quality: 75
            filters:
                scale:
                    dim: [1280, 720]