liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    driver:               "gd"
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeActio
    filter_sets: 
        square1: # The name of the filter, can be later used in the twig template 
            quality: 100 # Compression quality, this image will be 75% the quality 
            filters: 
                # These are the filters of the filter set, many filters can be applied 
                # Scale and shrink the image to the given size, with a possible crop of the image 
                thumbnail: 
                    size: [200, 200] 
                    mode: outbound
        square: # The name of the filter, can be later used in the twig template 
            quality: 100 # Compression quality, this image will be 75% the quality 
            filters: 
                # These are the filters of the filter set, many filters can be applied 
                # Scale and shrink the image to the given size, with a possible crop of the image 
                thumbnail: 
                    size: [200, 200] 
                    mode: outbound
        