# config/packages/presta_sitemap.yaml
presta_sitemap:
    defaults:
        priority: 1
        changefreq: daily
        lastmod: now
    default_section: default
    route_annotation_listener: false
    alternate:
        enabled: true
        default_locale: 'es'
        locales: ['es', 'pt', 'en', 'ge']
        i18n: symfony
