twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'cms/custom/vich_form_fields.html.twig'
        - 'cms/form/blocks_collection_row.html.twig'

    globals:
        languages: '%app.languages%'
        regions: '%app.regions%'
        block_types: '%app.block_types%'
        language_switcher: '%app.language_switcher%'
        navigation_service: '@App\Controller\Web\NavigationService'
        social_key: '%app.social.key%'