vich_uploader:
    db_driver: orm
    mappings:
        resources:
            uri_prefix: '%app.path.uploads.resources%'
            upload_destination: '%kernel.project_dir%/public%app.path.uploads.resources%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true