vich_uploader:
    db_driver: orm
    mappings:
        lawyers:
            uri_prefix: upload/lawyers
            upload_destination: '%kernel.project_dir%/public/upload/lawyers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true