web:
    resource:       routes/web_routes.yaml
    prefix:         /{_locale}/{_region}
    requirements:
        _locale:   es|en|pt|zh
        _region:   sp|lt|pt|uk|de
    defaults:
        _locale:    '%app.default_language%'
        _region:    sp

cms:
    resource:       routes/cms_routes.yaml
    prefix:         /cms
    defaults:
        _locale:    es