web:
    resource:       routes/web_routes.yaml
    prefix:         /{_locale}/{_region}
    requirements:
        _locale:   es|en|pt|ge
        _region:   spain|latam|portugal|global
    defaults:
        _locale:    '%app.default_language%'
        _region:    spain
    

cms:
    resource:       routes/cms_routes.yaml
    prefix:         /cms
    defaults:
        _locale:    es

api:
    resource:       routes/api_routes.yaml
    prefix:         /api
    defaults:
        _locale:    es