# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    # Languages & Translations
    app.languages: [es, en, pt]     # The list of available languages
    app.default_language: es        # The default language

    locale: '%app.default_language%'  # A parameter referenced from the Doctrine Behaviours configuration

    app.regions: [spain, latam, portugal, global]

    # The Single Sign On configuration parameters
    app.single_sign_on:
        url: 'http://srvwebinta.cuatrecasas.com/VSNET/WebServicesCGP/Credentials/Service.svc?wsdl'
        options:
            trace: 1
            exception: 0
    app.lawyer_types:
        - associate
        - counsel
        - honorary_partner
        - honorary_president
        - managing_partner
        - no_position
        - partner
        - senior_associate
        - senior_partner

    app.known_languages_by_lawyers: [es, en, it, pt, fr]

    app.event_types:
        - standard
        - webinar
        - breakfast
        - institutional
    app.block_types:
        - quoteBlock
        - eventsBlock
    app.path.uploads.resources: '/resources'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/Repository/PublishableEntityRepository.php'
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\MigrationCommand:
        tags:
            - { name: 'console.command', command: 'app:migration' }

    App\Security\TokenAuthenticator:
        arguments:
            $singleSignOnParameters: '%app.single_sign_on%'

# KnpLab Paginator
knp_paginator:
    template:
        #sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v3_sortable_link.html.twig'
        #sortable: '@KnpPaginator/Pagination/font_awesome_sortable_link.html.twig'
        #sortable: '@KnpPaginator/Pagination/semantic_ui_sortable_link.html.twig'
        #filtration: '@KnpPaginator/Pagination/filtration.html.twig'
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'